FlowRouter.route("/",{
	action : function(params,queryParams) {
       BlazeLayout.render("mainpage",{});
	}
});
FlowRouter.route('/contact',{
    name:'About',
    action(){
    	BlazeLayout.render('contact');
    }
});
FlowRouter.route('/diseñoydesarrollo',{
    name:'About',
    action(){
    	BlazeLayout.render('diseñoydesarrollo');
    }
});
FlowRouter.route('/html5',{
    name:'About',
    action(){
    	BlazeLayout.render('html5');
    }
});
FlowRouter.route('/nodejs',{
    name:'About',
    action(){
    	BlazeLayout.render('nodejs');
    }
});
FlowRouter.route('/saber',{
    name:'About',
    action(){
    	BlazeLayout.render('saber');
    }
});
